### ISSUE TITLE
How do I view the elm/html examples?

### ISSUE THREAD

**Issue by kyclark** [bryanjenningz/25-elm-examples#1]
First off, excellent code!  Thanks bigly.  How do I compile/view the 21-25 examples?

**Comment by bryanjenningz** [comment]
Thanks for opening this issue! I'll write instructions in the README. You have 2 options.

1) You can use Ellie, which has everything set up. The links to the Ellie programs are in the README. Here's a link to example 21: https://ellie-app.com/3wR7QgwzngSa1/20

2) You can also compile and view examples 21-25 locally. To do this, you can do the following commands:
```
git clone https://github.com/bryanjenningz/25-elm-examples.git
cd 25-elm-examples
elm-make 21-localstorage-editable-todos.elm --output elm.js --yes
open 21-localstorage-editable-todos.html
```

Let me know if these options work for you.

**Comment by bryanjenningz** [comment]
I added an explanation to the README. Thanks again for telling me about this. If there are any other issues or if any parts of the code are difficult to understand, let me know and I'll try to fix them.
