### ISSUE TITLE
Last 2 examples are missing comments

### ISSUE THREAD

**Issue by jhrcek** [bryanjenningz/25-elm-examples#2]
Hello Bryan,
thank you for this great tutorial! Could you please also add "what's changed from previous version" comments to the last 2 examples? It's not clear what changed given the code size and especially basic info about how routing works would be useful.
And another minor thing: links to ellie in the readme should be renamed to match file names of the elm files

**Comment by bryanjenningz** [comment]
Thanks for opening this issue! I just added comments for 24 and 25 and I changed the link text in the readme to match the file names of the Elm files.

**Comment by jhrcek** [comment]
Thank you! :)
