### ISSUE TITLE
awesome, thank you for these examples!

### ISSUE THREAD

**Issue by benkoshy** [bryanjenningz/25-elm-examples#5]

**Comment by benkoshy** [comment]
I was thinking that this might do well if structured as a series of progressive exercises with instructions: is it worth a PR?

**Comment by bryanjenningz** [comment]
This seems like a good idea. It will probably make this repo more easy to follow! Thanks for the PR too! https://github.com/bryanjenningz/25-elm-examples/pull/6
I added a comment to it.

**Comment by bryanjenningz** [comment]
Resolved. Thanks for the pull request! https://github.com/bryanjenningz/25-elm-examples/pull/6

**Comment by benkoshy** [comment]
ok i've added a few more instructions for lessons 3, 4 - please see the PR.

rgds
Ben
